/*
Arithmetic Operations API

API for performing basic arithmetic operations

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package calcssdkgo

import (
	"encoding/json"
)

// checks if the SubtractPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubtractPost200Response{}

// SubtractPost200Response struct for SubtractPost200Response
type SubtractPost200Response struct {
	Difference *float32 `json:"difference,omitempty"`
}

// NewSubtractPost200Response instantiates a new SubtractPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubtractPost200Response() *SubtractPost200Response {
	this := SubtractPost200Response{}
	return &this
}

// NewSubtractPost200ResponseWithDefaults instantiates a new SubtractPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubtractPost200ResponseWithDefaults() *SubtractPost200Response {
	this := SubtractPost200Response{}
	return &this
}

// GetDifference returns the Difference field value if set, zero value otherwise.
func (o *SubtractPost200Response) GetDifference() float32 {
	if o == nil || IsNil(o.Difference) {
		var ret float32
		return ret
	}
	return *o.Difference
}

// GetDifferenceOk returns a tuple with the Difference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtractPost200Response) GetDifferenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Difference) {
		return nil, false
	}
	return o.Difference, true
}

// HasDifference returns a boolean if a field has been set.
func (o *SubtractPost200Response) HasDifference() bool {
	if o != nil && !IsNil(o.Difference) {
		return true
	}

	return false
}

// SetDifference gets a reference to the given float32 and assigns it to the Difference field.
func (o *SubtractPost200Response) SetDifference(v float32) {
	o.Difference = &v
}

func (o SubtractPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubtractPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Difference) {
		toSerialize["difference"] = o.Difference
	}
	return toSerialize, nil
}

type NullableSubtractPost200Response struct {
	value *SubtractPost200Response
	isSet bool
}

func (v NullableSubtractPost200Response) Get() *SubtractPost200Response {
	return v.value
}

func (v *NullableSubtractPost200Response) Set(val *SubtractPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSubtractPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSubtractPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubtractPost200Response(val *SubtractPost200Response) *NullableSubtractPost200Response {
	return &NullableSubtractPost200Response{value: val, isSet: true}
}

func (v NullableSubtractPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubtractPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


