/*
Arithmetic Operations API

API for performing basic arithmetic operations

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package calcssdkgo

import (
	"encoding/json"
)

// checks if the SumPost400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SumPost400Response{}

// SumPost400Response struct for SumPost400Response
type SumPost400Response struct {
	Error *string `json:"error,omitempty"`
}

// NewSumPost400Response instantiates a new SumPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSumPost400Response() *SumPost400Response {
	this := SumPost400Response{}
	return &this
}

// NewSumPost400ResponseWithDefaults instantiates a new SumPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSumPost400ResponseWithDefaults() *SumPost400Response {
	this := SumPost400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SumPost400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SumPost400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SumPost400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *SumPost400Response) SetError(v string) {
	o.Error = &v
}

func (o SumPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SumPost400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableSumPost400Response struct {
	value *SumPost400Response
	isSet bool
}

func (v NullableSumPost400Response) Get() *SumPost400Response {
	return v.value
}

func (v *NullableSumPost400Response) Set(val *SumPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSumPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSumPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSumPost400Response(val *SumPost400Response) *NullableSumPost400Response {
	return &NullableSumPost400Response{value: val, isSet: true}
}

func (v NullableSumPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSumPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


