/*
Arithmetic Operations API

API for performing basic arithmetic operations

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package calcssdkgo

import (
	"encoding/json"
)

// checks if the SubtractPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubtractPostRequest{}

// SubtractPostRequest struct for SubtractPostRequest
type SubtractPostRequest struct {
	// List of numbers to subtract
	Numbers []float32 `json:"numbers,omitempty"`
}

// NewSubtractPostRequest instantiates a new SubtractPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubtractPostRequest() *SubtractPostRequest {
	this := SubtractPostRequest{}
	return &this
}

// NewSubtractPostRequestWithDefaults instantiates a new SubtractPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubtractPostRequestWithDefaults() *SubtractPostRequest {
	this := SubtractPostRequest{}
	return &this
}

// GetNumbers returns the Numbers field value if set, zero value otherwise.
func (o *SubtractPostRequest) GetNumbers() []float32 {
	if o == nil || IsNil(o.Numbers) {
		var ret []float32
		return ret
	}
	return o.Numbers
}

// GetNumbersOk returns a tuple with the Numbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtractPostRequest) GetNumbersOk() ([]float32, bool) {
	if o == nil || IsNil(o.Numbers) {
		return nil, false
	}
	return o.Numbers, true
}

// HasNumbers returns a boolean if a field has been set.
func (o *SubtractPostRequest) HasNumbers() bool {
	if o != nil && !IsNil(o.Numbers) {
		return true
	}

	return false
}

// SetNumbers gets a reference to the given []float32 and assigns it to the Numbers field.
func (o *SubtractPostRequest) SetNumbers(v []float32) {
	o.Numbers = v
}

func (o SubtractPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubtractPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Numbers) {
		toSerialize["numbers"] = o.Numbers
	}
	return toSerialize, nil
}

type NullableSubtractPostRequest struct {
	value *SubtractPostRequest
	isSet bool
}

func (v NullableSubtractPostRequest) Get() *SubtractPostRequest {
	return v.value
}

func (v *NullableSubtractPostRequest) Set(val *SubtractPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubtractPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubtractPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubtractPostRequest(val *SubtractPostRequest) *NullableSubtractPostRequest {
	return &NullableSubtractPostRequest{value: val, isSet: true}
}

func (v NullableSubtractPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubtractPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


